GET_DEFENSE_METRICS_QUERY = """select * from adam_custom.test.ml_defense"""

GET_OFFENSE_METRICS_QUERY = """select * from adam_custom.ml_offense"""

GET_ODDS_QUERY = """select odds_by_team.week,
    odds_by_team.season,
        CASE
            WHEN odds_by_team.gametime > '20:00'::text THEN 1
            ELSE 0
        END AS primetime,
    odds_by_team.team,
        CASE
            WHEN odds_by_team.location = 'Home'::text THEN 1
            ELSE 0
        END AS is_home,
    odds_by_team.opponent as oponnent,
    odds_by_team.is_neutral::integer AS is_neutral,
    odds_by_team.rest,
    odds_by_team.opponent_rest,
    odds_by_team.projected_total,
    odds_by_team.actual_score
from games.odds_by_team"""

CREATE_PLAY_BY_PLAY_QUERY = """
DROP TABLE IF EXISTS raw.play_by_play;

CREATE TABLE raw.play_by_play (
	play_id int8 NULL,
	game_id text NULL,
	old_game_id int8 NULL,
	home_team text NULL,
	away_team text NULL,
	season_type text NULL,
	week int8 NULL,
	posteam text NULL,
	posteam_type text NULL,
	defteam text NULL,
	side_of_field text NULL,
	yardline_100 float8 NULL,
	game_date text NULL,
	quarter_seconds_remaining float8 NULL,
	half_seconds_remaining float8 NULL,
	game_seconds_remaining float8 NULL,
	game_half text NULL,
	quarter_end int8 NULL,
	drive float8 NULL,
	sp int8 NULL,
	qtr int8 NULL,
	down float8 NULL,
	goal_to_go float8 NULL,
	"time" text NULL,
	yrdln text NULL,
	ydstogo int8 NULL,
	ydsnet float8 NULL,
	"desc" text NULL,
	play_type text NULL,
	yards_gained float8 NULL,
	shotgun int8 NULL,
	no_huddle int8 NULL,
	qb_dropback float8 NULL,
	qb_kneel int8 NULL,
	qb_spike int8 NULL,
	qb_scramble int8 NULL,
	pass_length text NULL,
	pass_location text NULL,
	air_yards float8 NULL,
	yards_after_catch float8 NULL,
	run_location text NULL,
	run_gap text NULL,
	field_goal_result text NULL,
	kick_distance float8 NULL,
	extra_point_result text NULL,
	two_point_conv_result text NULL,
	home_timeouts_remaining int8 NULL,
	away_timeouts_remaining int8 NULL,
	timeout float8 NULL,
	timeout_team text NULL,
	td_team text NULL,
	td_player_name text NULL,
	td_player_id text NULL,
	posteam_timeouts_remaining float8 NULL,
	defteam_timeouts_remaining float8 NULL,
	total_home_score int8 NULL,
	total_away_score int8 NULL,
	posteam_score float8 NULL,
	defteam_score float8 NULL,
	score_differential float8 NULL,
	posteam_score_post float8 NULL,
	defteam_score_post float8 NULL,
	score_differential_post float8 NULL,
	no_score_prob float8 NULL,
	opp_fg_prob float8 NULL,
	opp_safety_prob float8 NULL,
	opp_td_prob float8 NULL,
	fg_prob float8 NULL,
	safety_prob float8 NULL,
	td_prob float8 NULL,
	extra_point_prob float8 NULL,
	two_point_conversion_prob float8 NULL,
	ep float8 NULL,
	epa float8 NULL,
	total_home_epa float8 NULL,
	total_away_epa float8 NULL,
	total_home_rush_epa float8 NULL,
	total_away_rush_epa float8 NULL,
	total_home_pass_epa float8 NULL,
	total_away_pass_epa float8 NULL,
	air_epa float8 NULL,
	yac_epa float8 NULL,
	comp_air_epa float8 NULL,
	comp_yac_epa float8 NULL,
	total_home_comp_air_epa float8 NULL,
	total_away_comp_air_epa float8 NULL,
	total_home_comp_yac_epa float8 NULL,
	total_away_comp_yac_epa float8 NULL,
	total_home_raw_air_epa float8 NULL,
	total_away_raw_air_epa float8 NULL,
	total_home_raw_yac_epa float8 NULL,
	total_away_raw_yac_epa float8 NULL,
	wp float8 NULL,
	def_wp float8 NULL,
	home_wp float8 NULL,
	away_wp float8 NULL,
	wpa float8 NULL,
	vegas_wpa float8 NULL,
	vegas_home_wpa float8 NULL,
	home_wp_post float8 NULL,
	away_wp_post float8 NULL,
	vegas_wp float8 NULL,
	vegas_home_wp float8 NULL,
	total_home_rush_wpa float8 NULL,
	total_away_rush_wpa float8 NULL,
	total_home_pass_wpa float8 NULL,
	total_away_pass_wpa float8 NULL,
	air_wpa float8 NULL,
	yac_wpa float8 NULL,
	comp_air_wpa float8 NULL,
	comp_yac_wpa float8 NULL,
	total_home_comp_air_wpa float8 NULL,
	total_away_comp_air_wpa float8 NULL,
	total_home_comp_yac_wpa float8 NULL,
	total_away_comp_yac_wpa float8 NULL,
	total_home_raw_air_wpa float8 NULL,
	total_away_raw_air_wpa float8 NULL,
	total_home_raw_yac_wpa float8 NULL,
	total_away_raw_yac_wpa float8 NULL,
	punt_blocked float8 NULL,
	first_down_rush float8 NULL,
	first_down_pass float8 NULL,
	first_down_penalty float8 NULL,
	third_down_converted float8 NULL,
	third_down_failed float8 NULL,
	fourth_down_converted float8 NULL,
	fourth_down_failed float8 NULL,
	incomplete_pass float8 NULL,
	touchback int8 NULL,
	interception float8 NULL,
	punt_inside_twenty float8 NULL,
	punt_in_endzone float8 NULL,
	punt_out_of_bounds float8 NULL,
	punt_downed float8 NULL,
	punt_fair_catch float8 NULL,
	kickoff_inside_twenty float8 NULL,
	kickoff_in_endzone float8 NULL,
	kickoff_out_of_bounds float8 NULL,
	kickoff_downed float8 NULL,
	kickoff_fair_catch float8 NULL,
	fumble_forced float8 NULL,
	fumble_not_forced float8 NULL,
	fumble_out_of_bounds float8 NULL,
	solo_tackle float8 NULL,
	safety float8 NULL,
	penalty float8 NULL,
	tackled_for_loss float8 NULL,
	fumble_lost float8 NULL,
	own_kickoff_recovery float8 NULL,
	own_kickoff_recovery_td float8 NULL,
	qb_hit float8 NULL,
	rush_attempt float8 NULL,
	pass_attempt float8 NULL,
	sack float8 NULL,
	touchdown float8 NULL,
	pass_touchdown float8 NULL,
	rush_touchdown float8 NULL,
	return_touchdown float8 NULL,
	extra_point_attempt float8 NULL,
	two_point_attempt float8 NULL,
	field_goal_attempt float8 NULL,
	kickoff_attempt float8 NULL,
	punt_attempt float8 NULL,
	fumble float8 NULL,
	complete_pass float8 NULL,
	assist_tackle float8 NULL,
	lateral_reception float8 NULL,
	lateral_rush float8 NULL,
	lateral_return float8 NULL,
	lateral_recovery float8 NULL,
	passer_player_id text NULL,
	passer_player_name text NULL,
	passing_yards float8 NULL,
	receiver_player_id text NULL,
	receiver_player_name text NULL,
	receiving_yards float8 NULL,
	rusher_player_id text NULL,
	rusher_player_name text NULL,
	rushing_yards float8 NULL,
	lateral_receiver_player_id text NULL,
	lateral_receiver_player_name text NULL,
	lateral_receiving_yards float8 NULL,
	lateral_rusher_player_id text NULL,
	lateral_rusher_player_name text NULL,
	lateral_rushing_yards float8 NULL,
	lateral_sack_player_id float8 NULL,
	lateral_sack_player_name float8 NULL,
	interception_player_id text NULL,
	interception_player_name text NULL,
	lateral_interception_player_id text NULL,
	lateral_interception_player_name text NULL,
	punt_returner_player_id text NULL,
	punt_returner_player_name text NULL,
	lateral_punt_returner_player_id text NULL,
	lateral_punt_returner_player_name text NULL,
	kickoff_returner_player_name text NULL,
	kickoff_returner_player_id text NULL,
	lateral_kickoff_returner_player_id text NULL,
	lateral_kickoff_returner_player_name text NULL,
	punter_player_id text NULL,
	punter_player_name text NULL,
	kicker_player_name text NULL,
	kicker_player_id text NULL,
	own_kickoff_recovery_player_id text NULL,
	own_kickoff_recovery_player_name text NULL,
	blocked_player_id text NULL,
	blocked_player_name text NULL,
	tackle_for_loss_1_player_id text NULL,
	tackle_for_loss_1_player_name text NULL,
	tackle_for_loss_2_player_id text NULL,
	tackle_for_loss_2_player_name text NULL,
	qb_hit_1_player_id text NULL,
	qb_hit_1_player_name text NULL,
	qb_hit_2_player_id text NULL,
	qb_hit_2_player_name text NULL,
	forced_fumble_player_1_team text NULL,
	forced_fumble_player_1_player_id text NULL,
	forced_fumble_player_1_player_name text NULL,
	forced_fumble_player_2_team text NULL,
	forced_fumble_player_2_player_id text NULL,
	forced_fumble_player_2_player_name text NULL,
	solo_tackle_1_team text NULL,
	solo_tackle_2_team text NULL,
	solo_tackle_1_player_id text NULL,
	solo_tackle_2_player_id text NULL,
	solo_tackle_1_player_name text NULL,
	solo_tackle_2_player_name text NULL,
	assist_tackle_1_player_id text NULL,
	assist_tackle_1_player_name text NULL,
	assist_tackle_1_team text NULL,
	assist_tackle_2_player_id text NULL,
	assist_tackle_2_player_name text NULL,
	assist_tackle_2_team text NULL,
	assist_tackle_3_player_id text NULL,
	assist_tackle_3_player_name text NULL,
	assist_tackle_3_team text NULL,
	assist_tackle_4_player_id text NULL,
	assist_tackle_4_player_name text NULL,
	assist_tackle_4_team text NULL,
	tackle_with_assist float8 NULL,
	tackle_with_assist_1_player_id text NULL,
	tackle_with_assist_1_player_name text NULL,
	tackle_with_assist_1_team text NULL,
	tackle_with_assist_2_player_id text NULL,
	tackle_with_assist_2_player_name text NULL,
	tackle_with_assist_2_team text NULL,
	pass_defense_1_player_id text NULL,
	pass_defense_1_player_name text NULL,
	pass_defense_2_player_id text NULL,
	pass_defense_2_player_name text NULL,
	fumbled_1_team text NULL,
	fumbled_1_player_id text NULL,
	fumbled_1_player_name text NULL,
	fumbled_2_player_id text NULL,
	fumbled_2_player_name text NULL,
	fumbled_2_team text NULL,
	fumble_recovery_1_team text NULL,
	fumble_recovery_1_yards float8 NULL,
	fumble_recovery_1_player_id text NULL,
	fumble_recovery_1_player_name text NULL,
	fumble_recovery_2_team text NULL,
	fumble_recovery_2_yards float8 NULL,
	fumble_recovery_2_player_id text NULL,
	fumble_recovery_2_player_name text NULL,
	sack_player_id text NULL,
	sack_player_name text NULL,
	half_sack_1_player_id text NULL,
	half_sack_1_player_name text NULL,
	half_sack_2_player_id text NULL,
	half_sack_2_player_name text NULL,
	return_team text NULL,
	return_yards float8 NULL,
	penalty_team text NULL,
	penalty_player_id text NULL,
	penalty_player_name text NULL,
	penalty_yards float8 NULL,
	replay_or_challenge int8 NULL,
	replay_or_challenge_result text NULL,
	penalty_type text NULL,
	defensive_two_point_attempt float8 NULL,
	defensive_two_point_conv float8 NULL,
	defensive_extra_point_attempt float8 NULL,
	defensive_extra_point_conv float8 NULL,
	safety_player_name text NULL,
	safety_player_id text NULL,
	season int8 NULL,
	cp float8 NULL,
	cpoe float8 NULL,
	series int8 NULL,
	series_success int8 NULL,
	series_result text NULL,
	order_sequence float8 NULL,
	start_time text NULL,
	time_of_day text NULL,
	stadium text NULL,
	weather text NULL,
	nfl_api_id text NULL,
	play_clock float8 NULL,
	play_deleted float8 NULL,
	play_type_nfl text NULL,
	special_teams_play float8 NULL,
	st_play_type text NULL,
	end_clock_time text NULL,
	end_yard_line text NULL,
	fixed_drive int8 NULL,
	fixed_drive_result text NULL,
	drive_real_start_time text NULL,
	drive_play_count float8 NULL,
	drive_time_of_possession text NULL,
	drive_first_downs float8 NULL,
	drive_inside20 float8 NULL,
	drive_ended_with_score float8 NULL,
	drive_quarter_start float8 NULL,
	drive_quarter_end float8 NULL,
	drive_yards_penalized float8 NULL,
	drive_start_transition text NULL,
	drive_end_transition text NULL,
	drive_game_clock_start text NULL,
	drive_game_clock_end text NULL,
	drive_start_yard_line text NULL,
	drive_end_yard_line text NULL,
	drive_play_id_started float8 NULL,
	drive_play_id_ended float8 NULL,
	away_score int8 NULL,
	home_score int8 NULL,
	"location" text NULL,
	"result" int8 NULL,
	total int8 NULL,
	spread_line float8 NULL,
	total_line float8 NULL,
	div_game int8 NULL,
	roof text NULL,
	surface text NULL,
	"temp" float8 NULL,
	wind float8 NULL,
	home_coach text NULL,
	away_coach text NULL,
	stadium_id text NULL,
	game_stadium text NULL,
	aborted_play int8 NULL,
	success float8 NULL,
	passer text NULL,
	passer_jersey_number float8 NULL,
	rusher text NULL,
	rusher_jersey_number float8 NULL,
	receiver text NULL,
	receiver_jersey_number float8 NULL,
	pass int8 NULL,
	rush int8 NULL,
	first_down float8 NULL,
	special int8 NULL,
	play int8 NULL,
	passer_id text NULL,
	rusher_id text NULL,
	receiver_id text NULL,
	"name" text NULL,
	jersey_number float8 NULL,
	id text NULL,
	fantasy_player_name text NULL,
	fantasy_player_id text NULL,
	fantasy text NULL,
	fantasy_id text NULL,
	out_of_bounds int8 NULL,
	home_opening_kickoff int8 NULL,
	qb_epa float8 NULL,
	xyac_epa float8 NULL,
	xyac_mean_yardage float8 NULL,
	xyac_median_yardage float8 NULL,
	xyac_success float8 NULL,
	xyac_fd float8 NULL,
	xpass float8 NULL,
	pass_oe float8 NULL,
	CONSTRAINT play_by_play_play_id_game_id_down_key UNIQUE (play_id, game_id)
);
"""

CREATE_PLAYERS_QUERY = """
DROP TABLE IF EXISTS raw.players;

CREATE TABLE raw.players (
	status text NULL,
	display_name text NULL,
	first_name text NULL,
	last_name text NULL,
	esb_id text NULL,
	gsis_id text NULL,
	birth_date text NULL,
	college_name text NULL,
	position_group text NULL,
	"position" text NULL,
	jersey_number float8 NULL,
	height float8 NULL,
	weight float8 NULL,
	years_of_experience float8 NULL,
	team_abbr text NULL,
	team_seq float8 NULL,
	current_team_id float8 NULL,
	football_name text NULL,
	gsis_it_id float8 NULL,
	smart_id text NULL,
	headshot text NULL,
	short_name text NULL,
	entry_year float8 NULL,
	rookie_year float8 NULL,
	draft_club text NULL,
	draft_number float8 NULL,
	college_conference text NULL,
	status_description_abbr text NULL,
	status_short_description text NULL,
	uniform_number text NULL,
	suffix text NULL,
	draft_round text NULL,
	season float8 NULL,
	CONSTRAINT players_mfl_id_key UNIQUE (esb_id, gsis_id)
);
"""

CREATE_WEEKLY_QUERY = """
DROP TABLE IF EXISTS raw.weekly;

CREATE TABLE raw.weekly (
    player_id text NULL,
	player_name text NULL,
	player_display_name text NULL,
	"position" text NULL,
	position_group text NULL,
	headshot_url text NULL,
	recent_team text NULL,
	season int8 NULL,
	week int8 NULL,
	season_type text NULL,
	opponent_team text NULL,
	completions int8 NULL,
	attempts int8 NULL,
	passing_yards int8 NULL,
	passing_tds int8 NULL,
	interceptions int8 NULL,
	sacks int8 NULL,
	sack_yards int8 NULL,
	sack_fumbles int8 NULL,
	sack_fumbles_lost int8 NULL,
	passing_air_yards int8 NULL,
	passing_yards_after_catch int8 NULL,
	passing_first_downs int8 NULL,
	passing_epa float8 NULL,
	passing_2pt_conversions int8 NULL,
	pacr float8 NULL,
	dakota float8 NULL,
	carries int8 NULL,
	rushing_yards int8 NULL,
	rushing_tds int8 NULL,
	rushing_fumbles int8 NULL,
	rushing_fumbles_lost int8 NULL,
	rushing_first_downs int8 NULL,
	rushing_epa float8 NULL,
	rushing_2pt_conversions int8 NULL,
	receptions int8 NULL,
	targets int8 NULL,
	receiving_yards int8 NULL,
	receiving_tds int8 NULL,
	receiving_fumbles int8 NULL,
	receiving_fumbles_lost int8 NULL,
	receiving_air_yards int8 NULL,
	receiving_yards_after_catch int8 NULL,
	receiving_first_downs int8 NULL,
	receiving_epa float8 NULL,
	receiving_2pt_conversions int8 NULL,
	racr float8 NULL,
	target_share float8 NULL,
	air_yards_share float8 NULL,
	wopr float8 NULL,
	special_teams_tds int8 NULL,
	fantasy_points float8 NULL,
	fantasy_points_ppr float8 NULL,
	CONSTRAINT weekly_player_id_week_season_key UNIQUE (player_id, week, season)
);
"""

CREATE_INJURIES_QUERY = """
DROP TABLE IF EXISTS raw.injuries;

CREATE TABLE raw.injuries (
	season float8 NULL,
	game_type text NULL,
	team text NULL,
	week float8 NULL,
	gsis_id text NULL,
	"position" text NULL,
	full_name text NULL,
	first_name text NULL,
	last_name text NULL,
	report_primary_injury text NULL,
	report_secondary_injury text NULL,
	report_status text NULL,
	practice_primary_injury text NULL,
	practice_secondary_injury text NULL,
	practice_status text NULL,
	date_modified timestamp NULL,
	CONSTRAINT injuries_gsis_id_season_week_team_key UNIQUE (gsis_id, season, week, team)
);
"""

CREATE_COMBINE_QUERY = """
DROP TABLE IF EXISTS raw.combine;

CREATE TABLE raw.combine (
	season int4 NULL,
	draft_year float8 NULL,
	draft_team text NULL,
	draft_round float8 NULL,
	draft_ovr float8 NULL,
	pfr_id text NULL,
	cfb_id text NULL,
	player_name text NULL,
	pos text NULL,
	school text NULL,
	ht text NULL,
	wt float8 NULL,
	forty float8 NULL,
	bench float8 NULL,
	vertical float8 NULL,
	broad_jump float8 NULL,
	cone float8 NULL,
	shuttle float8 NULL,
	CONSTRAINT combine_player_name_season_draft_team_pos_key UNIQUE (player_name, season, draft_team, pos)
);
"""

CREATE_NGS_RUSHING_QUERY = """
DROP TABLE IF EXISTS raw.rushing_next_gen_stats;

CREATE TABLE raw.rushing_next_gen_stats (
	season int4 NULL,
	season_type text NULL,
	week int4 NULL,
	player_display_name text NULL,
	player_position text NULL,
	team_abbr text NULL,
	efficiency float8 NULL,
	percent_attempts_gte_eight_defenders float8 NULL,
	avg_time_to_los float8 NULL,
	rush_attempts int4 NULL,
	rush_yards int4 NULL,
	expected_rush_yards float8 NULL,
	rush_yards_over_expected float8 NULL,
	avg_rush_yards float8 NULL,
	rush_yards_over_expected_per_att float8 NULL,
	rush_pct_over_expected float8 NULL,
	rush_touchdowns int4 NULL,
	player_gsis_id text NULL,
	player_first_name text NULL,
	player_last_name text NULL,
	player_jersey_number int4 NULL,
	player_short_name text NULL,
	CONSTRAINT rushing_next_gen_stats_player_gsis_id_season_week_key UNIQUE (player_gsis_id, season, week)
);
"""

CREATE_NGS_RECEIVING_QUERY = """
DROP TABLE IF EXISTS raw.receiving_next_gen_stats;

CREATE TABLE raw.receiving_next_gen_stats (
	season int4 NULL,
	season_type text NULL,
	week int4 NULL,
	player_display_name text NULL,
	player_position text NULL,
	team_abbr text NULL,
	avg_cushion float8 NULL,
	avg_separation float8 NULL,
	avg_intended_air_yards float8 NULL,
	percent_share_of_intended_air_yards float8 NULL,
	receptions int4 NULL,
	targets int4 NULL,
	catch_percentage float8 NULL,
	yards float8 NULL,
	rec_touchdowns int4 NULL,
	avg_yac float8 NULL,
	avg_expected_yac float8 NULL,
	avg_yac_above_expectation float8 NULL,
	player_gsis_id text NULL,
	player_first_name text NULL,
	player_last_name text NULL,
	player_jersey_number int4 NULL,
	player_short_name text NULL,
	CONSTRAINT receiving_next_gen_stats_player_gsis_id_season_week_key UNIQUE (player_gsis_id, season, week)
);
"""

CREATE_NGS_PASSING_QUERY = """
DROP TABLE IF EXISTS raw.passing_next_gen_stats;


CREATE TABLE raw.passing_next_gen_stats (
	season int4 NULL,
	season_type text NULL,
	week int4 NULL,
	player_display_name text NULL,
	player_position text NULL,
	team_abbr text NULL,
	avg_time_to_throw float8 NULL,
	avg_completed_air_yards float8 NULL,
	avg_intended_air_yards float8 NULL,
	avg_air_yards_differential float8 NULL,
	aggressiveness float8 NULL,
	max_completed_air_distance float8 NULL,
	avg_air_yards_to_sticks float8 NULL,
	attempts int4 NULL,
	pass_yards int4 NULL,
	pass_touchdowns int4 NULL,
	interceptions int4 NULL,
	passer_rating float8 NULL,
	completions int4 NULL,
	completion_percentage float8 NULL,
	expected_completion_percentage float8 NULL,
	completion_percentage_above_expectation float8 NULL,
	avg_air_distance float8 NULL,
	max_air_distance float8 NULL,
	player_gsis_id text NULL,
	player_first_name text NULL,
	player_last_name text NULL,
	player_jersey_number int4 NULL,
	player_short_name text NULL,
	CONSTRAINT passing_next_gen_stats_player_gsis_id_season_week_key UNIQUE (player_gsis_id, season, week)
);
"""

CREATE_DEPTH_CHARTS_QUERY = """
DROP TABLE IF EXISTS raw.depth_charts;

CREATE TABLE raw.depth_charts (
	season float8 NULL,
	club_code text NULL,
	week float8 NULL,
	game_type text NULL,
	depth_team text NULL,
	last_name text NULL,
	first_name text NULL,
	football_name text NULL,
	formation text NULL,
	gsis_id text NULL,
	jersey_number text NULL,
	"position" text NULL,
	elias_id text NULL,
	depth_position text NULL,
	full_name text NULL,
	CONSTRAINT depth_charts_gsis_id_season_week_depth_position_depth_team__key UNIQUE (gsis_id, season, week, depth_position, depth_team, game_type, formation, club_code)
);
"""

CREATE_PFR_RUSHING_QUERY = """
DROP TABLE IF EXISTS raw.rushing_pro_football_reference;

CREATE TABLE raw.rushing_pro_football_reference (
	game_id text NULL,
	pfr_game_id text NULL,
	season int4 NULL,
	week int4 NULL,
	game_type text NULL,
	team text NULL,
	opponent text NULL,
	pfr_player_name text NULL,
	pfr_player_id text NULL,
	carries float8 NULL,
	rushing_yards_before_contact float8 NULL,
	rushing_yards_before_contact_avg float8 NULL,
	rushing_yards_after_contact float8 NULL,
	rushing_yards_after_contact_avg float8 NULL,
	rushing_broken_tackles float8 NULL,
	receiving_broken_tackles float8 NULL,
	CONSTRAINT rushing_pro_football_reference_pfr_game_id_pfr_player_id_key UNIQUE (pfr_game_id, pfr_player_id)
);
"""

CREATE_PFR_RECEIVING_QUERY = """
DROP TABLE IF EXISTS raw.receiving_pro_football_reference;

CREATE TABLE raw.receiving_pro_football_reference (
	game_id text NULL,
	pfr_game_id text NULL,
	season int4 NULL,
	week int4 NULL,
	game_type text NULL,
	team text NULL,
	opponent text NULL,
	pfr_player_name text NULL,
	pfr_player_id text NULL,
	rushing_broken_tackles float8 NULL,
	receiving_broken_tackles float8 NULL,
	passing_drops float8 NULL,
	passing_drop_pct float8 NULL,
	receiving_drop float8 NULL,
	receiving_drop_pct float8 NULL,
	receiving_int float8 NULL,
	receiving_rat float8 NULL,
	CONSTRAINT receiving_pro_football_reference_pfr_game_id_pfr_player_id_key UNIQUE (pfr_game_id, pfr_player_id)
);
"""

CREATE_PFR_PASSING_QUERY = """
DROP TABLE IF EXISTS raw.passing_pro_football_reference;


CREATE TABLE raw.passing_pro_football_reference (
	game_id text NULL,
	pfr_game_id text NULL,
	season int4 NULL,
	week int4 NULL,
	game_type text NULL,
	team text NULL,
	opponent text NULL,
	pfr_player_name text NULL,
	pfr_player_id text NULL,
	passing_drops float8 NULL,
	passing_drop_pct float8 NULL,
	receiving_drop float8 NULL,
	receiving_drop_pct float8 NULL,
	passing_bad_throws float8 NULL,
	passing_bad_throw_pct float8 NULL,
	times_sacked float8 NULL,
	times_blitzed float8 NULL,
	times_hurried float8 NULL,
	times_hit float8 NULL,
	times_pressured float8 NULL,
	times_pressured_pct float8 NULL,
	def_times_blitzed float8 NULL,
	def_times_hurried float8 NULL,
	def_times_hitqb float8 NULL,
	CONSTRAINT passing_pro_football_reference_pfr_game_id_pfr_player_id_key UNIQUE (pfr_game_id, pfr_player_id)
);
"""

CREATE_SNAPS_QUERY = """
DROP TABLE IF EXISTS raw.snaps;

CREATE TABLE raw.snaps (
	game_id text NULL,
	pfr_game_id text NULL,
	season int4 NULL,
	game_type text NULL,
	week int4 NULL,
	player text NULL,
	pfr_player_id text NULL,
	"position" text NULL,
	team text NULL,
	opponent text NULL,
	offense_snaps float8 NULL,
	offense_pct float8 NULL,
	defense_snaps float8 NULL,
	defense_pct float8 NULL,
	st_snaps float8 NULL,
	st_pct float8 NULL,
	CONSTRAINT snaps_pfr_game_id_pfr_player_id_key UNIQUE (pfr_game_id, pfr_player_id)
);
"""

CREATE_FTN_QUERY = """
DROP TABLE IF EXISTS raw.ftn;

CREATE TABLE raw.ftn (
	ftn_game_id int8 NULL,
	nflverse_game_id text NULL,
	season int8 NULL,
	week int8 NULL,
	ftn_play_id int8 NULL,
	nflverse_play_id int8 NULL,
	starting_hash text NULL,
	qb_location text NULL,
	n_offense_backfield float8 NULL,
	n_defense_box float8 NULL,
	is_no_huddle bool NULL,
	is_motion bool NULL,
	is_play_action bool NULL,
	is_screen_pass bool NULL,
	is_rpo bool NULL,
	is_trick_play bool NULL,
	is_qb_out_of_pocket bool NULL,
	is_interception_worthy bool NULL,
	is_throw_away bool NULL,
	read_thrown text NULL,
	is_catchable_ball bool NULL,
	is_contested_ball bool NULL,
	is_created_reception bool NULL,
	is_drop bool NULL,
	is_qb_sneak bool NULL,
	n_blitzers int8 NULL,
	n_pass_rushers float8 NULL,
	is_qb_fault_sack bool NULL,
	date_pulled text NULL,
	CONSTRAINT ftn_ftn_game_id_ftn_play_id_key UNIQUE (ftn_game_id, ftn_play_id)
);
"""

CREATE_WEEKLY_ROSTERS_QUERY = """
DROP TABLE IF EXISTS raw.rosters;

CREATE TABLE raw.rosters (
	season int8 NULL,
	team text NULL,
	"position" text NULL,
	depth_chart_position text NULL,
	jersey_number text NULL,
	status text NULL,
	full_name text NULL,
	first_name text NULL,
	last_name text NULL,
	birth_date text NULL,
	height float8 NULL,
	weight float8 NULL,
	college text NULL,
	gsis_id text NULL,
	espn_id float8 NULL,
	sportradar_id text NULL,
	yahoo_id text NULL,
	rotowire_id float8 NULL,
	pff_id float8 NULL,
	pfr_id text NULL,
	fantasy_data_id float8 NULL,
	sleeper_id float8 NULL,
	years_exp float8 NULL,
	headshot_url text NULL,
	ngs_position text NULL,
	week int8 NULL,
	game_type text NULL,
	status_description_abbr text NULL,
	football_name text NULL,
	esb_id text NULL,
	gsis_it_id float8 NULL,
	smart_id text NULL,
	entry_year float8 NULL,
	rookie_year float8 NULL,
	draft_club text NULL,
	draft_number float8 NULL,
	CONSTRAINT weekly_rosters_season_week_position_full_name_pfr_id_status_key UNIQUE (season, week, "position", full_name, pfr_id, status, team)
);
"""

CREATE_GAME_ODDS_QUERY = """
DROP TABLE IF EXISTS raw.odds;

CREATE TABLE raw.odds (
	game_id text NULL,
	season int8 NULL,
	game_type text NULL,
	week int8 NULL,
	gameday text NULL,
	weekday text NULL,
	gametime text NULL,
	away_team text NULL,
	away_score float8 NULL,
	home_team text NULL,
	home_score float8 NULL,
	"location" text NULL,
	"result" float8 NULL,
	total float8 NULL,
	overtime float8 NULL,
	old_game_id int8 NULL,
	gsis float8 NULL,
	nfl_detail_id text NULL,
	pfr text NULL,
	pff float8 NULL,
	espn int8 NULL,
	ftn float8 NULL,
	away_rest int8 NULL,
	home_rest int8 NULL,
	away_moneyline float8 NULL,
	home_moneyline float8 NULL,
	spread_line float8 NULL,
	away_spread_odds float8 NULL,
	home_spread_odds float8 NULL,
	total_line float8 NULL,
	under_odds float8 NULL,
	over_odds float8 NULL,
	div_game int8 NULL,
	roof text NULL,
	surface text NULL,
	"temp" float8 NULL,
	wind float8 NULL,
	away_qb_id text NULL,
	home_qb_id text NULL,
	away_qb_name text NULL,
	home_qb_name text NULL,
	away_coach text NULL,
	home_coach text NULL,
	referee text NULL,
	stadium_id text NULL,
	stadium text NULL,
	insert_date date NULL,
	CONSTRAINT game_odds_game_id_insert_date_key UNIQUE (insert_date, game_id)
);"""
